#! /bin/sh

GAP=5
PAD=50

#. "/home/elf/.cache/wal/color.sh"

#bspc config normal_border_color "#b9b9b9"
#bspc config active_border_color "#b9b9b9"
#bspc config focused_border_color "$#b9b9b9"
bspc config presel_feedback_color "#b9b9b9"

/home/elf/.config/bspwm/autostart

cd /home/elf/Documents/scripts/shell

bash bspwm-multimonitor.sh

bspc config border_width         0
bspc config window_gap           $GAP
bspc config top_padding          $PAD
bspc config bottom_padding       $PAD
bspc config left_padding         $PAD
bspc config right_padding        $PAD

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config focus_follows_pointer true
